apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "helm-chart-ssc-pipeline.fullname" . }}
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: GIT-URL
    type: string
  - name: GIT-REVISION
    type: string
    default: main
  - name: IMAGE_REPO
    type: string
  - name: IMAGE_TAG
    type: string
  - name: CYCLONEDX_HOST_URL 
    type: string
  tasks:
  # 1. Git Clone
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.GIT-URL)
        - name: revision
          value: $(params.GIT-REVISION)
  # 2. ACS image scan
    - name: acs-image-scan  
      params:  
        - name: rox_central_endpoint
          value: stackrox-endpoint
        - name: rox_api_token
          value: stackrox-secret
        - name: image
          value: $(params.IMAGE_REPO):$(params.IMAGE_TAG)
        - name: insecure-skip-tls-verify  
          value: 'true'
      runAfter:  
        - git-clone
      taskRef:
        kind: Task
        name: acs-image-scan
  # 3. ACS image check  
    - name: acs-image-check  
      params:  
        - name: rox_central_endpoint
          value: stackrox-endpoint
        - name: rox_api_token
          value: stackrox-secret
        - name: image
          value: $(params.image)
        - name: insecure-skip-tls-verify  
          value: 'true'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: acs-image-check
  # 4. SBOM generation  
    - name: generate-sbom 
      params:
        - name: cyclonedxHostUrl
          value: $(params.CYCLONEDX_HOST_URL)
      runAfter:
        - acs-image-scan
        - acs-image-check
      taskRef:
        kind: Task
        name: generate-sbom
      workspaces:
        - name: repository
          workspace: shared-workspace
  # 5. kube linter
    - name: kube-linter
      runAfter:
        - generate-sbom
      taskRef:
      name: kube-linter
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: manifest
          value: helm
        - name: default_option
          value: do-not-auto-add-defaults
        - name: includelist
          value: "no-extensions-v1beta,default-service-account,no-readiness-probe"