kind: Secret
apiVersion: v1
metadata:
  name: stackrox-secret
  namespace: ci
data:
  rox_api_token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklt
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: stackrox-endpoint
  namespace: ci
stringData:
  rox_central_endpoint: central-stackrox.apps.cluster-8n7zx.8n7zx.sandbox2467.opentlc.com:443
type: Opaque 